### PR TITLE
Add filepaths [drag&]drop callback support

### PR DESCRIPTION
**Pull request by Peaker**

### CODE REVIEW

**Comment by schell** [comment]
Hi @Peaker - thanks for your help, although this addition is already present in the additions-3.1 branch which exists to serve #48.

**Comment by Peaker** [comment]
Oh, why link all these changes together?

Could be nice to have the features available as they are coded...

**Comment by schell** [comment]
Yeah, that's a good point. I think linking them together just kept everything in sync.

I'll go ahead and merge what I have so far.

**Comment by Peaker** [comment]
Great, thanks!

**Pull request closed without merging**
